### ISSUE TITLE
rendering to the same page

### ISSUE THREAD

**Issue by cmjlee3** [cmjlee3/project-2#1]
I have a router.post where I am trying to render multiple things to multiple pages. The original plan was to render all to the same page, but since that wasn't working I am now trying to render them to separate pages... what's happening when I use the below is the second and third renders and being over ridden by the first, and all pages /resultsLine and /resultsPlus are leading to /resultsLyft.

-also having difficulty working with save and delete

router.post('/', getRide, (req, res) => {
    console.log(res.saved);
    res.render('./resultsLyft', {
    results: res.saved.ops[0].lyft || [],
  });
    res.render('./resultsLine', {
      resultsLine: res.saved.ops[0].lyftLine || [],
    });
    res.render('./resultsPlus', {
      resultsPlus: res.saved.ops[0].lyftPlus || [],
    });
})

**Comment by cmjlee3** [comment]
@gittheking
@trevorpreston
@rapala61
@irwintsay

**Comment by rapala61** [comment]
Add me as a collaborator please
