### ISSUE TITLE
delete method

### ISSUE THREAD

**Issue by cmjlee3** [cmjlee3/project-2#2]
cannot get my delete method functioning, i've tried variations of the action for the last few hours but no luck :/

router:
router.delete('/lyft/:id', deleteRide, (req, res) => {
  res.redirect('show');
});

ejs:
<form action="/show/ <%= results._id %>?_method=DELETE" method="POST">
    <input type="submit" value="Delete">
  </form>

model: 

function deleteRide(req, res, next) {
  console.log('=========' +req.params.id)
  getDB().then((db) => {
    if (err) return next(err);

    db.collection('ride')
      .findAndRemove({ _id: ObjectID(req.params.id) }, (removeErr, doc) => {
        if(removeErr) return next(removeErr);

        res.removed = doc;
        // console.log("from models =====" + res.removed);
        db.close();
        return next();
      });
      return false;
  });
  return false;
}

**Comment by cmjlee3** [comment]
@gittheking
@trevorpreston
@rapala61
@irwintsay

**Comment by gittheking** [comment]
@cmjlee3, your form has a delete action of `/show/ <%= results._id %>?_method=DELETE`,  but your route as defined has a `router.delete('/lyft/:id', deleteRide, (req, res) => {`, so your form's action should have a value of `/show/lyft/<%= results._id %>?_method=DELETE`
